#!/usr/bin/env zsh

DOTFILES=$HOME/.dragons
STOW_FOLDERS="config,tmux,zsh,emacs,vim"
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	echo "==== Removing $folder ===="
	stow --verbose=3 -D $folder
done
popd
