#!/usr/bin/env zsh

if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle

DOTFILES=$HOME/.dragons
STOW_FOLDERS="config,tmux,zsh,emacs,vim"
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	echo "==== $folder ===="
	stow --verbose=2 -D $folder
	stow --verbose=2 $folder
done
popd
