#!/usr/bin/env zsh

DOTFILES=$HOME/.dragons
STOW_FOLDERS="config,tmux,zsh,emacs,vim"
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
	echo "==== $folder ===="
	stow --verbose=2 -D $folder
	stow --verbose=2 $folder
done
popd
